<a href="https://colab.research.google.com/github/jkjh23/2020_AI_Busan/blob/master/4_DL/08_pyTorch%20%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pyTorch(파이토치)

- [파이토치 시작하기](https://pytorch.org/get-started/locally/)
  - 개발 환경에 따라 설치하는 조합이 잘 나와있다.
  - 실제로 구축해보면, pyTorch가 CUDA와 가장 잘 연동된다.
  - CUDA vs ROCm : 현재 CUDA만 지원

## 특징

- Define by Run 방식
- 파이썬 짜듯이 작성 가능
- 디버깅 용이, 즉시 확인 가능
- numpy 베이스로 작동
  - Scipy, Numpy, Cython
  

In [ ]:
import torch

In [ ]:
torch.__version__
# 최신 버전으로 적용되어 있다.

'1.6.0+cu101'

- <img src="https://drive.google.com/uc?id=1PzcpfZlUc6Aovz9PsAq0Y-PJIm3ZcIg8" width="80%">
- pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# 텐서

- 텐서플로, 파이토치 등은 텐서를 기반으로 진행되는 연산을 수행하고, 딥러닝은 이런 연산의 연속이다.
- 딥러닝 연산의 기본 단위
- 행렬
- <img src="https://drive.google.com/uc?id=1GXInEu6qtFuzp-OkoiH6RFGcpYanV7RM" width="100%">



In [ ]:
# 텐서 생성
# 리스트, 배열로부터 생성 가능
# 기본 자료형 float32

In [ ]:
# 리스트
list_src = [[10,11,12], [13,14,15]]   # (2,3)
# 텐서 생성
x = torch.Tensor(list_src)
x

tensor([[10., 11., 12.],
        [13., 14., 15.]])

In [ ]:
# 텐서를 다시 리스트로 변환
x.tolist()

[[10.0, 11.0, 12.0], [13.0, 14.0, 15.0]]

In [ ]:
# 배열 생성
import numpy as np
arr = np.array(list_src)
arr
# 원래 타입대로 값이 적용(텐서는 float으로 변함)

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
# 생성 : 배열을 재료로
x = torch.Tensor(arr)
x

tensor([[10., 11., 12.],
        [13., 14., 15.]])

In [ ]:
# 텐서를 다시 배열로 변환
x.numpy()
# 복원은 됐으나 원래 타입으로 돌아가지 않는다.

array([[10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

# GPU 사용

In [ ]:
# 현재 device는 cpu
x.device

device(type='cpu')

In [ ]:
try : 
  # x라는 텐서에 device를 지정
  x.to('cuda')
  # 텐서별로 지정 가능
  print(x.device)
except Exception as e :
  pass